/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconEpBicycle: typeof import('~icons/ep/bicycle')['default']
    IconEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IconEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    IconEpCoordinate: typeof import('~icons/ep/coordinate')['default']
    IconEpFlag: typeof import('~icons/ep/flag')['default']
    IconEpGoodsFilled: typeof import('~icons/ep/goods-filled')['default']
    IconEpGrid: typeof import('~icons/ep/grid')['default']
    IconEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IconEpKey: typeof import('~icons/ep/key')['default']
    IconEpList: typeof import('~icons/ep/list')['default']
    IconEpPictureFilled: typeof import('~icons/ep/picture-filled')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    IconEpTicket: typeof import('~icons/ep/ticket')['default']
    IconEpUser: typeof import('~icons/ep/user')['default']
    IconEpVideoCameraFilled: typeof import('~icons/ep/video-camera-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
